name:                advent2019
version:             0.1.0.0
github:              "JonathanFraser/Advent2019"
license:             BSD3
author:              "Jonathan Fraser"
maintainer:          "jonathanfras@github.com"
copyright:           "2019 Jonathan Fraser"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/day1#readme>

dependencies:
- base >= 4.7 && < 5
- array
- text
- mtl
- containers

library:
  source-dirs: src

executables:
  day1:
    main:                Main.hs
    source-dirs:         Day1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  day2:
    main:                Main.hs
    source-dirs:         Day2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - array
      - advent2019
  day3:
    main:                Main.hs
    source-dirs:         Day3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - containers
      - text
  day4:
    main:                Main.hs
    source-dirs:         Day4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - containers
      - text
  day5:
    main:                Main.hs
    source-dirs:         Day5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - advent2019
  day6:
    main:                Main.hs
    source-dirs:         Day6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - containers
  day7:
    main:                Main.hs
    source-dirs:         Day7
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - advent2019
  day8:
    main:                Main.hs
    source-dirs:         Day8
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - advent2019
      - text
      - containers
  day9:
    main:                Main.hs
    source-dirs:         Day9
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - advent2019
  day10:
    main:                Main.hs
    source-dirs:         Day10
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - advent2019
      - containers
  day11:
    main:                Main.hs
    source-dirs:         Day11
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - advent2019
      - containers
  day12:
    main:                Main.hs
    source-dirs:         Day12
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - linear
      - lens
  day13:
    main:                Main.hs
    source-dirs:         Day13
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2019
    - containers
  day14:
    main:                Main.hs
    source-dirs:         Day14
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - parsec 
    - parsec3-numbers